// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// elasticnet
Rcpp::List elasticnet(arma::mat& XTX, arma::vec& XTY, double lam2, double lam1);
RcppExport SEXP _fasterElasticNet_elasticnet(SEXP XTXSEXP, SEXP XTYSEXP, SEXP lam2SEXP, SEXP lam1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type XTX(XTXSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type XTY(XTYSEXP);
    Rcpp::traits::input_parameter< double >::type lam2(lam2SEXP);
    Rcpp::traits::input_parameter< double >::type lam1(lam1SEXP);
    rcpp_result_gen = Rcpp::wrap(elasticnet(XTX, XTY, lam2, lam1));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fasterElasticNet_elasticnet", (DL_FUNC) &_fasterElasticNet_elasticnet, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_fasterElasticNet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
