# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

elasticnet <- function(XTX, XTY, lam2, lam1 = -1) {
    .Call(`_fasterElasticNet_elasticnet`, XTX, XTY, lam2, lam1)
}

