# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

elasticnetcpp <- function(XTX, XTY, lam2, lam1 = -1) {
    .Call(`_fasterElasticNet_elasticnetcpp`, XTX, XTY, lam2, lam1)
}

forupdate <- function(L, xxk, xkxk) {
    invisible(.Call(`_fasterElasticNet_forupdate`, L, xxk, xkxk))
}

givens <- function(L, k) {
    invisible(.Call(`_fasterElasticNet_givens`, L, k))
}

